/*Store Performance: Compare the performance of each store by calculating the total rentals
and revenue generated by each store.*/

SELECT 
  s.store_id, 
  COUNT(r.rental_id) AS total_rentals, 
  SUM(p.amount) AS revenue_$ 
FROM 
  store s 
JOIN 
  inventory i ON s.store_id = i.store_id
JOIN 
  rental r ON i.inventory_id = r.inventory_id
JOIN 
  payment p ON r.rental_id = p.rental_id
GROUP BY s.store_id
ORDER BY s.store_id ASC;
